In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [3]:
titanic = pd.read_csv('titanic.csv')

In [4]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
titanic.shape

(891, 12)

In [7]:
titanic['Sex'] = titanic['Sex'].map({'female':0, 'male':1})

In [21]:
tat = titanic[['Sex', 'Survived', 'Pclass', 'SibSp', 'Parch', 'Fare', 'Age']]

In [22]:
tat.head()

   Sex  Survived  Pclass  SibSp  Parch     Fare   Age
0    1         0       3      1      0   7.2500  22.0
1    0         1       1      1      0  71.2833  38.0
2    0         1       3      0      0   7.9250  26.0
3    0         1       1      1      0  53.1000  35.0
4    1         0       3      0      0   8.0500  35.0

In [23]:
tat.isnull().sum()

Sex           0
Survived      0
Pclass        0
SibSp         0
Parch         0
Fare          0
Age         177
dtype: int64

In [25]:
tat['Age'] = tat['Age'].fillna(tat['Age'].median())

In [29]:
tat.isnull().sum()

Sex         0
Survived    0
Pclass      0
SibSp       0
Parch       0
Fare        0
Age         0
dtype: int64

In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

In [31]:
x = tat.drop('Survived', axis=1)
y = tat['Survived']

In [32]:
x_train , x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [33]:
x_train.head()

     Sex  Pclass  SibSp  Parch     Fare   Age
331    1       1      0      0  28.5000  45.5
733    1       2      0      0  13.0000  23.0
382    1       3      0      0   7.9250  32.0
704    1       3      1      0   7.8542  26.0
813    0       3      4      2  31.2750   6.0

In [44]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(x_train, y_train)
model = rf.predict(x_test)

In [64]:
sample = x_test.iloc[0:1]
sample

     Sex  Pclass  SibSp  Parch     Fare   Age
709    1       3      1      1  15.2458  28.0

In [65]:
prediction = rf.predict(sample)

In [78]:
print(prediction[0:])

[0]

In [75]:
sample.iloc[0]

Sex        1.0000
Pclass     3.0000
SibSp      1.0000
Parch      1.0000
Fare      15.2458
Age       28.0000
Name: 709, dtype: float64

In [69]:

sample_dict = sample.iloc[0].to_dict()
print(f"\nSample Passenger: {sample_dict}")
print(f"Predicted Survival: {'Survived' if prediction[0] == 1 else 'Did Not Survive'}")

Sample Passenger: {'Sex': 1.0, 'Pclass': 3.0, 'SibSp': 1.0, 'Parch': 1.0, 'Fare': 15.2458, 'Age': 28.0}
Predicted Survival: Did Not Survive

In [46]:
y_pred

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1])

In [47]:
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.80

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.85      0.84       105
           1       0.77      0.74      0.76        74

    accuracy                           0.80       179
   macro avg       0.80      0.80      0.80       179
weighted avg       0.80      0.80      0.80       179